import os
import site
import time
import requests
import numpy as np
import sounddevice as sd
from pynput import keyboard

# Fix Windows DLL path for PyTorch CUDA binaries if present
try:
    os.add_dll_directory(os.path.join(site.getsitepackages()[0], "torch", "lib"))
except Exception:
    pass

from faster_whisper import WhisperModel
from kokoro import KPipeline

# ==========================================
# CONFIGURATION & INITIALIZATION
# ==========================================
OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
# MODEL_NAME = "qwen2.5-coder:7b"
MODEL_NAME = "qwen3.5:9b"
AUDIO_FILE = "user_input.wav"
SAMPLE_RATE = 16000  # 16kHz required by Whisper
 
 
print("Loading Whisper STT Model...")
# Use device="cuda" if you have an NVIDIA GPU, otherwise "cpu"
# stt_model = WhisperModel("small.en", device="cuda", compute_type="float16")
stt_model = WhisperModel("small.en", device="cpu", compute_type="int8")

print("Loading Kokoro TTS Engine...")
# 'a' stands for American English
tts_pipeline = KPipeline(lang_code="a")

# System prompt directing the LLM to behave like a technical interviewer
SYSTEM_PROMPT = (
    "You are an expert technical interviewer conducting a mock interview. "
    "Keep your responses concise, professional, and limited to 2-3 sentences. "
    "Ask relevant follow-up questions based on the candidate's answer."
)

# Maintain conversation history
conversation_history = SYSTEM_PROMPT + "\n"

# ==========================================
# HELPER FUNCTIONS
# ==========================================

def record_audio(filename, duration=15, samplerate=SAMPLE_RATE):
    """Records microphone input for a specified duration."""
    print(f"\n🎤 [Recording for {duration} seconds... Speak now!]")
    audio = sd.rec(int(duration * samplerate), samplerate=samplerate, channels=1, dtype='float32')
    sd.wait()
    sf.write(filename, audio, samplerate)
    print("✓ Recording complete.")

def transcribe_audio(filename):
    """Transcribes WAV file to text using faster-whisper."""
    print("⚡ Transcribing audio...")
    segments, _ = stt_model.transcribe(filename, beam_size=5)
    transcript = " ".join([segment.text for segment in segments]).strip()
    return transcript

def query_ollama(prompt):
    """Sends user text to Ollama and gets the text response."""
    global conversation_history
    conversation_history += f"\nCandidate: {prompt}\nInterviewer:"
    
    payload = {
        "model": MODEL_NAME,
        "prompt": conversation_history,
        "stream": False
    }
    
    response = requests.post(OLLAMA_URL, json=payload).json()
    ai_response = response.get("response", "").strip()
    
    # Save response back to history
    conversation_history += f" {ai_response}"
    return ai_response

def speak_text(text):
    """Synthesizes text to speech using Kokoro and plays it immediately."""
    print(f"\n🤖 Interviewer: {text}\n")
    print("🔊 Speaking...")
    
    # Generate audio chunks using Kokoro (voice 'af_sarah' or 'am_puck')
    generator = tts_pipeline(text, voice="am_puck", speed=1.0)
    
    for _, _, audio_array in generator:
        # Play 24kHz audio output generated by Kokoro
        sd.play(audio_array, samplerate=24000)
        sd.wait()

# ==========================================
# MAIN INTERVIEW LOOP
# ==========================================

def main():
    print("==================================================")
    print("   LOCAL AI VOICE INTERVIEW PRACTICE APP READY    ")
    print("==================================================")
    
    # Initial greeting from the interviewer
    initial_greeting = "Welcome! Let's start the interview. Can you briefly introduce yourself and your background in software engineering?"
    speak_text(initial_greeting)
    
    while True:
        input("\nPress [ENTER] to start recording your response (or Ctrl+C to quit)...")
        
        # 1. Record User Voice Input (15 seconds)
        record_audio(AUDIO_FILE, duration=15)
        
        # 2. STT: Transcribe Audio to Text
        user_text = transcribe_audio(AUDIO_FILE)
        print(f" You said: \"{user_text}\"")
        
        if not user_text:
            print("⚠️ No speech detected. Please try speaking again.")
            continue
            
        # 3. LLM: Query Ollama Brain
        print("🧠 Thinking...")
        ai_reply = query_ollama(user_text)
        
        # 4. TTS: Convert LLM text to voice & play back
        speak_text(ai_reply)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nInterview session ended. Good luck with your preparation!")